# Generated by Django 6.0 on 2026-01-09 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('Home & Garden', 'Home & Garden'), ('Electronics', 'Electronics'), ('Sports Gear', 'Sports Gear'), ('Fashion', 'Fashion'), ('Tools', 'Tools'), ('Kids & Toys', 'Kids & Toys')], max_length=20)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=20)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
