# Generated by Django 6.0 on 2026-01-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='seller',
        ),
    ]
