# Generated by Django 6.0 on 2026-01-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_system', '0003_listing_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10, verbose_name='Price Type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='rent_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Required only if price_type is "rent"', max_length=10, null=True, verbose_name='Rent Period'),
        ),
    ]
