# Generated by Django 6.0 on 2026-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_system', '0004_listing_price_type_listing_rent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
