# Generated by Django 6.0 on 2026-01-14 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing_system', '0005_listing_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Home & Garden', 'Home & Garden'), ('Electronics', 'Electronics'), ('Sports Gear', 'Sports Gear'), ('Fashion', 'Fashion'), ('Tools', 'Tools'), ('Kids & Toys', 'Kids & Toys')], max_length=20),
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listing_system.listing')),
            ],
        ),
    ]
